### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by AnishDubey27** [Anamika1-cpu/BlogsBee#2]
### Proposed feature
I think the details provided in the readme file might not be sufficient for a new contributor to start making contributions.
We can make some changes in the file which makes the process of contributing easier with a step by step contributing process.

### Possible use cases for the feature
This would be helpful for the first-time/new contributors to start contributing.
Also the project will get contributions from many new contributors.

#### I would like to work on this issue and contribute to the project.

**Comment by Anamika1-cpu** [comment]
I assigned the issue to you @AnishDubey27
